NotesApp/Controllers/CategoriesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using NotesApp.Controllers.CustomAuthorizeAttributes;
using NotesApp.Controllers.CustomNotesAttributes;
using NotesApp.DbStuff.Models.Notes;
using NotesApp.DbStuff.Repositories.Interfaces.Notes;
using NotesApp.Enum;
using NotesApp.Models.Notes;
using NotesApp.Services;

namespace NotesApp.Controllers;

[ApiGroup("Notes")]
[Authorize]
public class CategoriesController : Controller
{
    private ICategoryRepository _categoryRepository;
    private IAuthNotesService _authNotesService;

    public CategoriesController(ICategoryRepository categoryRepository, IAuthNotesService authNotesService)
    {
        _categoryRepository = categoryRepository;
        _authNotesService = authNotesService;
    }
    public IActionResult Index()
    {
        var canDelete = _authNotesService.IsAuthenticated() &&
                        (_authNotesService.GetRole() == NotesUserRole.Administrator ||
                         _authNotesService.GetRole() == NotesUserRole.Moderator);

        var categoryViewModels = _categoryRepository
            .GetAll()
            .Select(x => new CategoryViewModel
            {
                Id = x.Id,
                Name = x.Name,
                IsAllowedToDelete = canDelete
            })
            .ToList();

        return View(categoryViewModels);
    }
    
    // /Categories/Add (GET)
    [HttpGet]
    [RoleNotes(NotesUserRole.Administrator, NotesUserRole.Moderator, NotesUserRole.User)]
    public IActionResult Add()
    {
        return View();
    }

    // /Categories/Add (POST)
    [HttpPost]
    [RoleNotes(NotesUserRole.Administrator, NotesUserRole.Moderator, NotesUserRole.User)]
    public IActionResult Add(CategoryViewModel viewModel)
    {
        
        if (!ModelState.IsValid)
        {
            return View(viewModel);
        }

        var category = new Category
        {
            Name = viewModel.Name,
            CreateDate = DateTime.UtcNow,
            UpdateDate = DateTime.UtcNow
        };

        _categoryRepository.Add(category);

        return RedirectToAction("Index", "Notes");
    }

    [HttpGet]
    [RoleNotes(NotesUserRole.Administrator, NotesUserRole.Moderator)]
    public IActionResult Remove(int id)
    {
        _categoryRepository.Remove(id);

        return RedirectToAction("Index");
    }
}

NotesApp/Controllers/TagsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using NotesApp.Controllers.CustomAuthorizeAttributes;
using NotesApp.Controllers.CustomNotesAttributes;
using NotesApp.DbStuff.Models.Notes;
using NotesApp.DbStuff.Repositories.Interfaces.Notes;
using NotesApp.Enum;
using NotesApp.Models.Notes;
using NotesApp.Services;

namespace NotesApp.Controllers;

[ApiGroup("Notes")]
[Authorize]
public class TagsController : Controller
{
    private ITagRepository _tagRepository;
    private IAuthNotesService _authNotesService;

    public TagsController(ITagRepository tagRepository, IAuthNotesService authNotesService)
    {
        _tagRepository = tagRepository;
        _authNotesService = authNotesService;
    }
    public IActionResult Index()
    {
        var canDelete = _authNotesService.IsAuthenticated() &&
                        (_authNotesService.GetRole() == NotesUserRole.Administrator ||
                         _authNotesService.GetRole() == NotesUserRole.Moderator);

        var tagViewModels = _tagRepository
            .GetAll()
            .Select(x => new TagViewModel
            {
                Id = x.Id,
                Name = x.Name,
                IsAllowedToDelete = canDelete
            })
            .ToList();

        return View(tagViewModels);
    }

    // /Tags/Add (GET)
    [HttpGet]
    [RoleNotes(NotesUserRole.Administrator, NotesUserRole.Moderator, NotesUserRole.User)]
    public IActionResult Add()
    {
        return View();
    }

    // /Tags/Add (POST)
    [HttpPost]
    [RoleNotes(NotesUserRole.Administrator, NotesUserRole.Moderator, NotesUserRole.User)]
    public IActionResult Add(TagViewModel viewModel)
    {
        if (!ModelState.IsValid)
        {
            return View(viewModel);
        }

        var tag = new Tag
        {
            Name = viewModel.Name,
            CreateDate = DateTime.UtcNow,
            UpdateDate = DateTime.UtcNow
        };

        _tagRepository.Add(tag);

        return RedirectToAction("Index", "Notes");
    }

    [HttpGet]
    [RoleNotes(NotesUserRole.Administrator, NotesUserRole.Moderator)]
    public IActionResult Remove(int id)
    {
        _tagRepository.Remove(id);

        return RedirectToAction("Index");
    }
}

NotesApp/Views/Shared/_LayoutNotes.cshtml
@using NotesApp.Localizations.Notes
@using NotesApp.Services
@inject IAuthNotesService AuthNotesService

<!DOCTYPE html>

<html>
<head>
    <meta charset="UTF-8">
    <title>Notes</title>
    <link href="~/css/notes.css" rel="stylesheet"/>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/js/notes/global.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/styles/github.min.css" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/highlight.min.js"></script>
    <script>
        document.addEventListener("DOMContentLoaded", function () {
            if (window.hljs) {
                hljs.highlightAll();
            }
        });
    </script>
    @RenderSection("Scripts", false)
</head>
<body>
<div class="header">
    <div class="logo">
        <a href="/Notes">
            <img src="~/images/notes/logo.png" alt="Logo">
            <h1>Notes</h1>
        </a>
    </div>
    <div class="search">
        <input type="text" placeholder="Search">
    </div>
    <div class="header-right">
        @if (AuthNotesService.IsAuthenticated())
        {
            <a asp-area="" asp-controller="Notes" asp-action="Add" class="btn create-note-btn">
                + Создать заметку
            </a>
        }
        <div class="profile">
            @if (AuthNotesService.IsAuthenticated())
            {
                <div class="user-info">
                    <img src="~/@AuthNotesService.GetUser().AvatarUrl" alt="Avatar">
                    <span class="nickname">@AuthNotesService.GetUser().UserName (@AuthNotesService.GetId())</span>
                </div>
                <div class="dropdown">
                    <ul>
                        <li class="nav-item">
                            <a asp-area="" asp-controller="UserNotes" asp-action="Profile">@Notes.Index_menu_profile</a>
                        </li>
                        <li class="nav-item">
                            <a asp-area="" asp-controller="Notes" asp-action="Add">@Notes.Index_menu_add_note</a>
                        </li>
                        <li class="nav-item">
                            <a asp-area="" asp-controller="Categories"
                               asp-action="Add">@Notes.Index_menu_add_category</a>
                        </li>
                        <li class="nav-item">
                            <a asp-area="" asp-controller="Tags" asp-action="Add">@Notes.Index_menu_add_tag</a>
                        </li>
                        <li>
                            <a asp-area="" asp-controller="AuthNotes" asp-action="logout">@Notes.Index_menu_logout</a>
                        </li>
                    </ul>
                </div>
            }
            else
            {
                <div class="auth-links">
                    <a asp-area="" asp-controller="AuthNotes" asp-action="Login">@Notes.Index_menu_login</a>
                    <a asp-area="" asp-controller="AuthNotes"
                       asp-action="Registration">@Notes.Index_menu_registration</a>
                </div>
                <div class="user-info">
                    <img src="~/images/notes/avatars/guest.png" alt="Avatar">
                    <span class="nickname">Guest (0)</span>
                </div>
            }
        </div>
    </div>    
</div>
@RenderBody()
<div class="footer">
    <div class="copyright">Copyright 2025 A.Levadniy.</div>
    <div class="contacts">Contact info</div>
</div>
</body>
</html>